/*
 * ADC_CONF.h
 *
 *  Created on: Mar 1, 2023
 *      Author: Omar Alaa
 */

#ifndef ADC_CONF_H_
#define ADC_CONF_H_



/* ADC_VOLTAGE_SELECT
 *
ADC_REF_AREF_clr_msk
ADC_REF_AREF
ADC_REF_AVCC
ADC_REF_INT_2.56*/

#define ADC_VOLTAGE_SELECT   ADC_REF_AVCC


#define ADC_VOLTAGE_REF_mv     5000
#define ADC_MAX_NO.OFSTEPS     1024         /*(2^10)*/


/*ADC MODE SELECT
 *
ADC_MODE_AUTO_TRIGGER
ADC_MODE_SINGLE_CONVERSION  */

#define ADC_MODE_SELECT   ADC_MODE_AUTO_TRIGGER


/*ADC ADJUST SELECT

ADC_RIGHT_ADJUSTED
ADC_LEFT_ADJUSTED   */

#define ADC_ADJUST_SELECT     ADC_RIGHT_ADJUSTED


/* ADC PRESCALER SELECT

ADC_PRESCALER_clr_msk
ADC_PRESCALER_2
ADC_PRESCALER_4
ADC_PRESCALER_8
ADC_PRESCALER_16
ADC_PRESCALER_32
ADC_PRESCALER_64
ADC_PRESCALER_128
*/
#define ADC_PRESCALER_SELECT    ADC_PRESCALER_128



/*ADC AUTO TRIGGER SELECT

ADC_MODE_AUTO_TRIGGER_Source_msk
ADC_MODE_AUTO_TRIGGER_Source_free
ADC_MODE_AUTO_TRIGGER_Source_analog
ADC_MODE_AUTO_TRIGGER_Source_EXTI
ADC_MODE_AUTO_TRIGGER_Source_Compare_Match
ADC_MODE_AUTO_TRIGGER_Source_0overflow
ADC_MODE_AUTO_TRIGGER_Source_Compare_Match_B
ADC_MODE_AUTO_TRIGGER_Source_1overflow
ADC_MODE_AUTO_TRIGGER_Source_captur_event   */


#define ADC_AUTO_TRIGGER_SELECT    ADC_MODE_AUTO_TRIGGER_Source_free



#endif /* ADC_CONF_H_ */
